sudo: required

service: docker

# 
# for CI driver
#
language: python
python: 3.6

# TASK line is of the form <config>:<parameters>
# where <config> is a known config in tasks.py
#
# Each parameter is of the form of <kwd>=<value> or <kwd>+=<values> or <kwd>-=<values>
# where:
#   - <kwd> is a named keyword accepted by ci_task.copy function
#   - <value> can be:
#       - a string
#       - a list if ',' is present (i.e. "value," is the list [value] of one element)
#
#   - <kwd>+= is the same as add_<kwd>=
#   - <kwd>-= is the same as remove_<kwd>=
#
# If kwd is present several times, associated values must be lists. In
# this case a dictionay is incrementally built with the first element of the list as
# the key, and the remaining as the associated internal value. This
# concerns the targets keyword.
#
# Distributions are passed as lists of two elements, the first element
# is the name and the second the version.

env:
  - TASK=default:distrib=ubuntu,14.04
  - TASK=default:distrib=ubuntu,16.04
  - TASK=default:distrib=ubuntu,17.10
  - TASK=default:distrib=debian,latest
  - TASK=default:distrib=fedora,latest:pkgs-=atlas-lapack,:pkgs+=openblas-lapacke,
  - TASK=default:distrib=ubuntu,17.10:ci_config=with_cxx11
  - TASK=default:pkgs+=lpsolve,
  - TASK=default:pkgs-=atlas-lapack:pkgs+=openblas-lapacke,
  - TASK=default:ci_config=with_mumps:pkgs+=mumps,
  - TASK=default:ci_config=with_umfpack:pkgs+=umfpack,

# not finalized yet
# - TASK=default:ci_config=nix:distrib=nixos/nix,latest:targets=.,docker-build,docker-cmd:pkgs=cmake,make,siconos-nix-default,
# tasks too long for travis:
# - TASK=default:distrib=ubuntu,17.10:build_configuration=Profiling:pkgs+=profiling,
#  - TASK=default:distrib=ubuntu,17.10:ci_config=with_serialization:pkgs+=serialization,
# siconos package
#  - TASK=empty:docker=true:ci_config=examples_all:distrib=fedora,latest:pkgs=siconos,siconos-source:srcs=examples,:targets=examples,docker-build,docker-ctest
#  - TASK=empty:docker=true:ci_config=examples_all:distrib=ubuntu,16.04:pkgs=siconos,siconos-source:srcs=examples,:targets=examples,docker-build,docker-ctest

before_script:
  - case $TASK in
      *docker=false*)
        pip install lxml;
        pip install scipy
        ;;
      *)
        pip install pyyaml
        ;;
    esac
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task="$TASK" --packages-db=../CI/config/siconos.yml;
    else
      ../CI/driver.py --run --root-dir=.. --packages-db=../CI/config/siconos.yml;
    fi

