language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -y install python-software-properties
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get purge cmake -qq
  - sudo apt-get -y install aptitude
  - sudo aptitude -y install libboost-graph1.55-dev libboost-filesystem1.55-dev libboost-serialization1.55-dev
  - sudo aptitude -y install cmake gfortran gcc doxygen libatlas-base-dev libblas-dev libgmp3-dev libcppunit-dev libpcre3-dev python-matplotlib  python-numpy  python-scipy python-dev python-py make g++ git gccxml python-pygccxml python-lxml swig3.0 lp-solve liblpsolve55-dev python-logilab-common
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - sudo free -m
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCI_CONFIG=default ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - time make continuous
