version: 3.8.{build}

platform:
  - x64

environment:
  matrix:
    - MSYS2_ARCH: x86_64
install:
  - C:\msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -S gcc gcc-fortran && break || sleep 15; done"
  - appveyor DownloadFile "http://siconos.gforge.inria.fr/windows/siconos-dep.zip"
  - 7z x siconos-dep.zip

build_script:
  - set PATH=%PATH%;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin\opt\bin
  - mkdir builddir
  - cd builddir
  - C:\projects\siconos\Build\Windows\build-siconos-appveyor.bat C:\projects\siconos


os: Visual Studio 2015

notifications:
- provider: Email
  to:
  - ohuber2@wisc.edu
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
